In [1]:
import sys
sys.path.append('../package')
import lostark as lok
import pandas as pd
import pprint
import seaborn as sns
import matplotlib.pyplot as plt

import matplotlib.font_manager as fm
font_path = "C:/Users/user/Code_Files_Jupyter/nanum-all/나눔 글꼴/나눔바른고딕/NanumFontSetup_TTF_BARUNGOTHIC/NanumBarunGothic.ttf"
font_name = fm.FontProperties(fname=font_path).get_name()
fm.fontManager.addfont(font_path)
plt.rc('font', family='NanumBarunGothic')

pd.set_option('display.max_columns', None)

In [2]:
df = lok.get_table_df('engraving_table')

In [3]:
df.head(2)

,characterCode,grantName1,grantPoint1,grantName2,grantPoint2,engraving1_name,engraving1_level,engraving2_name,engraving2_level,engraving3_name,engraving3_level,engraving4_name,engraving4_level,engraving5_name,engraving5_level,engraving6_name,engraving6_level,engraving7_name,engraving7_level,engraving8_name,engraving8_level,engraving9_name,engraving9_level,engraving10_name,engraving10_level,engraving11_name,engraving11_level,engraving12_name,engraving12_level,engraving13_name,engraving13_level,engraving14_name,engraving14_level,engraving15_name,engraving15_level
0,1,원한,12,저주받은 인형,12.0,원한,3.0,저주받은 인형,3.0,공격속도 감소,1.0,공격력 감소,1.0,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,None,None,None,None,None
1,3,만개,9,만개,9.0,만개,3.0,중갑 착용,3.0,약자 무시,1.0,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,NaN,None,None,None,None,None,None

In [4]:
for i in range(0, len(df.columns), 20):
    df.iloc[:, i:i+20].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437407 entries, 0 to 437406
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   characterCode     437407 non-null  int64
 1   grantName1        437407 non-null  object
 2   grantPoint1       437407 non-null  int64
 3   grantName2        435127 non-null  object
 4   grantPoint2       435127 non-null  float64
 5   engraving1_name   437239 non-null  object
 6   engraving1_level  437239 non-null  float64
 7   engraving2_name   431981 non-null  object
 8   engraving2_level  431981 non-null  float64
 9   engraving3_name   419995 non-null  object
 10  engraving3_level  419995 non-null  float64
 11  engraving4_name   400967 non-null  object
 12  engraving4_level  400967 non-null  float64
 13  engraving5_name   341254 non-null  object
 14  engraving5_level  341254 non-null  float64
 15  engraving6_name   169330 non-null  object
 16  engraving6_level  169330 non-null  float64
 17  engraving7_name   19750 non-null   object
 18  engraving7_level  19750 non-null   float64
 19  engraving8_name   5100 non-null    object
dtypes: float64(8), int64(2), object(10)
memory usage: 66.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437407 entries, 0 to 437406
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   engraving8_level   5100 non-null   float64
 1   engraving9_name    1266 non-null   object
 2   engraving9_level   1266 non-null   float64
 3   engraving10_name   230 non-null    object
 4   engraving10_level  230 non-null    float64
 5   engraving11_name   35 non-null     object
 6   engraving11_level  35 non-null     float64
 7   engraving12_name   1 non-null      object
 8   engraving12_level  1 non-null      float64
 9   engraving13_name   0 non-null      object
 10  engraving13_level  0 non-null      object
 11  engraving14_name   0 non-null      object
 12  engraving14_level  0 non-null      object
 13  engraving15_name   0 non-null      object
 14  engraving15_level  0 non-null      object
dtypes: float64(5), object(10)
memory usage: 50.1+ MB

In [16]:
engravings = []
for i in range(1, 13):
    engravings += list(df[f'engraving{i}_name'].unique())
engravings = list(set(engravings))
engravings = [item for item in engravings if item is not None]
print(engravings)

['진실된 용맹', '불굴', '핸드거너', '일격필살', '멈출 수 없는 충동', '돌격대장', '마나 효율 증가', '화력 강화', '중갑 착용', '폭발물 전문가', '강화 무기', '질량 증가', '위기 모면', '부러진 뼈', '선수필승', '구슬동자', '시선 집중', '극의: 체술', '포식자', '번개의 분노', '탈출의 명수', '황후의 은총', '약자 무시', '고독한 기사', '광전사의 비기', '방어력 감소', '두 번째 동료', '각성', '분노의 망치', '실드 관통', '공격력 감소', '완벽한 억제', '역천지체', '충격 단련', '회귀', '정기 흡수', '예리한 둔기', '질풍노도', '처단자', '기습의 대가', '절정', '강화 방패', '만개', '에테르 포식자', '속전속결', '이슬비', '바리케이드', '급소 타격', '축복의 오라', '세맥타통', '승부사', '황제의 칙령', '아드레날린', '달인의 저력', '긴급구조', '원한', '오의 강화', '사냥의 시간', '정밀 단도', '여신의 가호', '달의 소리', '분쇄의 주먹', '강령술', '버스트', '저주받은 인형', '타격의 대가', '전투 태세', '피스메이커', '잔재된 기운', '갈증', '안정된 상태', '굳은 의지', '절제', '슈퍼 차지', '공격속도 감소', '절실한 구원', '광기', '만월의 집행자', '오의난무', '환류', '마나의 흐름', '포격 강화', '죽음의 습격', '넘치는 교감', '아르데타인의 기술', '최대 마나 증가', '초심', '중력 수련', '추진력', '심판자', '점화', '상급 소환사', '전문의', '진화의 유산', '그믐의 경계', '결투의 대가', '이동속도 감소']

In [ ]:
dfc = df.copy()
res = pd.DataFrame()
res['engraving_name'] = pd.concat([df[f'engraving{i}_name'] for i in range(1, 13, 2)], axis=0, ignore_index=True)
res['engraving_level'] = pd.concat([df[f'engraving{i}_level'] for i in range(2, 14, 2)], axis=0, ignore_index=True)
res.dropna(inplace=True)
res.groupby('engraving_name').sum().sort_values(by='engraving_level')

sns.barplot(x=res['engraving_level'], y=res['engraving_name'], orient='h')
plt.show()